### ISSUE TITLE
Permission and correct way to use the tree visualisation

### ISSUE THREAD

**Issue by boymalloy** [BenPortner/js_family_tree#17]
Hi,

I'm a big fan of your family tree visualisation. Really great work!

This isn't an issue with your code but is a question about the right way to use it within something.

I'm learning to make stuff in Python/flask and I've been building some stuff around your visualiser. I'm not actually changing anything in the JavaScript, but I'm writing Python code that takes a very simple csv of family members and outputs it as a json file that your tree visualisation can understand. This has helped me to learn about python, flask and jinja templates.

The thing is, I'm not sure whether I have used your code in the most friendly/normal/legit way, and I wanted to check how you would prefer me to do it? I haven't forked the repo coz I am not changing the JS code, just writing new Python ... but maybe I should have? (This is all new to me).

Here's my repo: https://github.com/boymalloy/python-flask-d3-family-tree

At the moment I have mentioned you and linked to your repo in my readme file, just like you linked to D3noob's repo in yours. Is that enough?  Please let me know if I need to do something else.

Thanks again for such an ace app!

Alex

**Comment by BenPortner** [comment]
Hello @boymalloy,

I checked your repo and you are using js_family_tree just in the way it is intended - for visualizations! Feel free to keep using it that way. I am glad to see great applications built around it :)

There is just one minor caveat: js_family_tree has a GPL3 license, which is copy-left. You already open sourced your application, which is one of the basic requirements to use dependencies with this license. Another requirement is that your program must be published under the exact same license. As far as I can see, your app does not have any license yet, which means that the source code is currently your own intellectual property and may not be used by anyone else. This means your app is currently not compatible with the GPL3 license - and may thus not use GPL3 dependencies, like my project. Luckily, this can be changed very easily by adding the GPL3 license to your own repository :)

Concerning the "best" way to integrate code into your project: Most people I know prefer to use npm to integrate Javascript code. Unfortunately, this is not an option here because I never published my project there (for reasons :P). Also, using package managers gets kind of messy with multi-language projects like yours. I believe what you did (copying the code manually and using it that way) is just fine. Another option that is a bit complicated to learn in the beginning but pays off fast for dependencies that change frequently is git submodules. Feel free to [have a look](https://git-scm.com/book/en/v2/Git-Tools-Submodules) :)

**Comment by boymalloy** [comment]
Hi Ben,

Thanks for getting back to me and for your advice. I will add the licence
and will check out the submodules link.

Thanks again.

Alex

**Comment by BenPortner** [comment]
You're welcome and thanks again for using js_family_tree :)
